### ISSUE TITLE
How to Check Android Device Availability via API Endpoint?

### ISSUE THREAD

**Issue by sinanouri** [capcom6/sms-gateway#70]
I am looking for an API endpoint or a procedure to check device availability, such as a health check.

The idea is to call a device health check endpoint, sending the device ID, and receive information on whether the device is online or not. This could include checking if the device's battery is dead or if the device is disconnected from the internet (e.g., a cellphone).

Is there a standard approach or best practice for implementing such a feature? Any example endpoints or code snippets would be highly appreciated.

I am aware of the health check endpoints, but:

`/api/api/3rdparty/v1/health` is returning:

```json
{
  "message": "Not Found"
}
```
`/health` only checks backend and database health.

1. What is the recommended way to implement a health check endpoint specifically for devices?
2. Are there any standard practices or patterns for such an implementation?
3. Can you provide example code snippets or endpoint designs for device health checks?

Thank you in advance for your help!

**Comment by capcom6** [comment]
Hello,

In Cloud mode, there isn't a direct way to check if a device is online because devices do not maintain a constant connection to the server. Instead, they receive PUSH notifications when there are new messages in the queue. This design is intentional to conserve battery power, as a permanent connection would deplete it quickly.

Regarding your questions:

0. It seems there's a typo in the path you mentioned: `/api/3rdparty/v1/health`. The correct path doesn’t duplicate the `/api` segment. And yes, this endpoint only verifies the health of the backend.
1. The ideal approach would be to use a Local Server Mode and send a request directly to the device. However, this may not be feasible if your device lacks a public IP or a way to be accessed directly from your application.
2. In Cloud mode, you can utilize the [`/device`](https://capcom6.github.io/android-sms-gateway/#/Devices/get-devices) endpoint. The response includes a `lastSeen` field. Nevertheless, due to Android's app idle state limitations, the system does not allow more than one request every 15 minutes. Consequently, this endpoint does not provide a real-time online status, but if a device hasn't been seen in the last 15 minutes, it could indicate a problem (although it's not guaranteed).
3. Here are some example commands:
   - For backend health: `curl https://sms.capcom.me/api/3rdparty/v1/health`
   - For device information: `curl https://sms.capcom.me/api/3rdparty/v1/device -u <login>:<password>`

Additionally, you may find this issue relevant: https://github.com/capcom6/android-sms-gateway/issues/61

**Comment by sinanouri** [comment]
I get the URL from api/swagger.json, and there is a double /api in the path.

I think it is a good idea to implement a procedure to get device health so we can use it in our system to monitor the device status. In case of any problems with the device, we can fix it.

**Comment by capcom6** [comment]
Thank you for bringing this to my attention! I'll make sure to update the documentation shortly to correct the double `/api` in the path.

As previously mentioned, providing real-time device status can significantly impact battery life. Since this feature may not be necessary for all users, I am considering a less resource-intensive solution, such as a "ping" endpoint. When this endpoint receives a "ping", it would trigger a PUSH notification to the device. If the device is online, it would then update its `lastSeen` timestamp exposed in the `/device` endpoint, as previously described. Would this approach meet your needs?

Additionally, understanding your specific use case in more detail could help me tailor a solution that better fits your requirements. Could you share more about how you plan to use the application?

If you'd prefer to discuss your use case in a more private setting, please feel free to reach out to me directly via email at i@capcom.me.

**Comment by sinanouri** [comment]
> Thank you for bringing this to my attention! I'll make sure to update the documentation shortly to correct the double `/api` in the path.
> 
> As previously mentioned, providing real-time device status can significantly impact battery life. Since this feature may not be necessary for all users, I am considering a less resource-intensive solution, such as a "ping" endpoint. When this endpoint receives a "ping", it would trigger a PUSH notification to the device. If the device is online, it would then update its `lastSeen` timestamp exposed in the `/device` endpoint, as previously described. Would this approach meet your needs?
> 
> Additionally, understanding your specific use case in more detail could help me tailor a solution that better fits your requirements. Could you share more about how you plan to use the application?
> 
> If you'd prefer to discuss your use case in a more private setting, please feel free to reach out to me directly via email at [i@capcom.me](mailto:i@capcom.me).

Yes the ping will be a great idea, and it will reduce 15 minute last seen to 1 minute or even seconds, i think it will be great if we could set the ping period in settings.

**Comment by capcom6** [comment]
Hello, @sinanouri !

I've prepared a draft version of the app with a ping function. You can find the APK in this PR: https://github.com/capcom6/android-sms-gateway/pull/85

I haven't created the documentation yet, but here are the main points:

1. The ping feature is activated on the device. In the "Ping" section of the settings, you can set the ping interval (a value of 0 or leaving it empty means no ping).
2. After changing the settings, restart the app using the "Online/Offline" button on the Home screen.
3. The icon of the ping service will appear in the status bar.

From here, you have two ways to determine the device's online status:

1. In Cloud/Private mode use the `GET /device` endpoint as described earlier. The `lastSeen` field will be updated with every ping.
2. Utilize the webhook feature. With every ping, the `system:ping` event is emitted and can be sent to your server. See the guide on how to register a webhook at https://sms.capcom.me/getting-started/webhooks/.
